const ENDPOINT_PROD = "https://rickandmortyapi.com/api";
const ENDPOINT = ENDPOINT_PROD;
const STATUS_CODE_DEFAULT = 99999;
const STATUS_MESSAGE_DEFAULT = "ATENÇÃO!, NÃO FOI POSSIVEL CONCLUIR A REQUISIÇÃO";
